[target.x86_64-theseus.dependencies]
compiler_builtins = { features = ["mem"] }
alloc = {}

[target.x86_64-theseus-sse.dependencies]
compiler_builtins = { features = ["mem"] }
alloc = {}

[target.x86_64-theseus-avx.dependencies]
compiler_builtins = { features = ["mem"] }
alloc = {}
